services:
  app:
    build: ./docker
    ports:
      - 8080:80
    volumes:
      - .:/var/www/devcontainer-laravel

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
